accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view


urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout")
]


app_name = "accounts"

gitlab_classroom/urls.py
from django.urls import path
from gitlab_classroom.views import (index,
                          ClassroomsListView,
                          AssignmentsListView,
                          ClassroomsDetailView,
                          AssignmentsDetailView,
                          ClassroomCreateView,
                          ClassroomUpdateView,
                          ClassroomDeleteView,
                          AssignmentCreateView,
                          AssignmentUpdateView,
                          AssignmentDeleteView,
                          StudentsListView,
                          StudentsDetailView,
                          StudentCreateView,
                          StudentUpdateView,
                          StudentDeleteView)


urlpatterns = [
    path("", index, name="index"),
    path("classrooms/", ClassroomsListView.as_view(), name="classroom-list"),
    path("assignments/", AssignmentsListView.as_view(), name="assignment-list"),
    path("classrooms/<int:pk>/", ClassroomsDetailView.as_view(), name="classroom-detail"),
    path("assignments/<int:pk>/", AssignmentsDetailView.as_view(), name="assignment-detail"),
    path("classrooms/<int:pk>/assignments/create/", AssignmentCreateView.as_view(), name="assignment-create"),
    path("assignments/<int:pk>/update/", AssignmentUpdateView.as_view(), name="assignment-update"),
    path("assignments/<int:pk>/delete/", AssignmentDeleteView.as_view(), name="assignment-delete"),
    path("classrooms/create/", ClassroomCreateView.as_view(), name="classroom-create"),
    path("classrooms/<int:pk>/update/", ClassroomUpdateView.as_view(), name="classroom-update"),
    path("classrooms/<int:pk>/delete/", ClassroomDeleteView.as_view(), name="classroom-delete"),
    path("students/", StudentsListView.as_view(), name="student-list"),
    path("students/<int:pk>/", StudentsDetailView.as_view(), name="student-detail"),
    path("students/create/", StudentCreateView.as_view(), name="student-create"),
    path("students/<int:pk>/update/", StudentUpdateView.as_view(), name="student-update"),
    path("students/<int:pk>/delete/", StudentDeleteView.as_view(), name="student-delete"),
]


app_name = "gitlab_classroom" 

gitlab_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gitlab_classroom.urls", namespace="gitlab_classroom")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("__debug__/", include("debug_toolbar.urls"))
]

gitlab_classroom/forms.py
from django import forms
from gitlab_classroom.models import Assignment, Student, Classroom


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ["title", "description", "template_id", "deadline"]
        widgets = {
            'deadline': forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'template_id': forms.TextInput(attrs={'type': 'text'}),
        }
        # It's important to specify the input format if you're using a custom format
        input_formats = ['%Y-%m-%dT%H:%M']

class AddStudentToClassroomForm(forms.Form):
    student = forms.ModelChoiceField(
        queryset=Student.objects.none(),  # Start with an empty queryset
        label="",
        required=True
    )

    def __init__(self, *args, **kwargs):
        classroom_id = kwargs.pop('classroom_id', None)
        super(AddStudentToClassroomForm, self).__init__(*args, **kwargs)
        if classroom_id:
            classroom = Classroom.objects.get(pk=classroom_id)
            # Exclude students who are already in this classroom
            self.fields['student'].queryset = Student.objects.exclude(id__in=classroom.students.all())


class RemoveStudentFromClassroomForm(forms.Form):
    student = forms.ModelChoiceField(queryset=Student.objects.none(), label="Select Student to Remove")


class ClassroomSearchForm(forms.Form):
    title = forms.CharField(max_length=255,
                            required=False,
                            label="",
                            widget=forms.TextInput(
                                attrs={
                                    "placeholder": "search by title"
                                }
                            )
                        )


class AssignmentSearchForm(forms.Form):
    title = forms.CharField(max_length=255,
                            required=False,
                            label="",
                            widget=forms.TextInput(
                                attrs={
                                    "placeholder": "search by title"
                                }
                            )
                        )


class StudentSearchForm(forms.Form):
    gitlab_username = forms.CharField(max_length=255,
                                      required=False,
                                      label="",
                                      widget=forms.TextInput(
                                          attrs={
                                              "placeholder":"search by username"
                                          }
                                    )
                                )

class UploadFileForm(forms.Form):
    file = forms.FileField(
        label=None,  # No label is displayed
        widget=forms.ClearableFileInput(attrs={
            'class': 'custom-file-input',  # Custom class for Bootstrap styling
            'id': 'customFile',  # Custom ID for the input element
        }),
    )

gitlab_classroom/views.py
import csv
import json
import gitlab
import re
from django.contrib.auth.decorators import login_required
from django.forms import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views import generic
from gitlab_classroom.forms import (ClassroomSearchForm,
                                    AssignmentSearchForm,
                                    StudentSearchForm,
                                    AddStudentToClassroomForm,
                                    UploadFileForm)
from gitlab_classroom.models import Classroom, Assignment, Student
from gitlab_classroom.forms import AssignmentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from gitlab import GitlabGetError


# Create your views here.
@login_required
def index(request: HttpResponse) -> HttpRequest:
    context = {
        "name": request.session["name"],
        "email": request.session["email"]
    }
    return render(request, "gitlab_classroom/index.html", context=context)


#this is a classbased representation of a classrooms
class ClassroomsListView(LoginRequiredMixin, generic.ListView):
    model = Classroom
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ClassroomsListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = ClassroomSearchForm(
            initial={"title": title}
        )
        return context

    def get_queryset(self):
        queryset = Classroom.objects.select_related("teacher").prefetch_related("students").filter(teacher=self.request.user)
        form = ClassroomSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        """Override to filter assignments to those owned by the current user."""
        return queryset


class ClassroomsDetailView(LoginRequiredMixin, generic.DetailView):
    model = Classroom
    context_object_name = 'classroom'
    template_name = 'gitlab_classroom/classroom_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        classroom_id = self.kwargs.get('pk')
        context['add_student_form'] = AddStudentToClassroomForm(classroom_id=classroom_id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        classroom_id = self.kwargs.get('pk')
        gl = gitlab.Gitlab('https://gitlab-stud.elka.pw.edu.pl', private_token=self.request.session["access_token"])
        if 'add_student' in request.POST:
            add_form = AddStudentToClassroomForm(request.POST, classroom_id=classroom_id)
            if add_form.is_valid():
                try:
                    group = gl.groups.get(self.object.gitlab_id)
                    subgroups = group.subgroups.list(all=True)
                    members_group = gl.groups.get(subgroups[1].id)
                    student = add_form.cleaned_data['student']
                    if subgroups:
                        member = members_group.members.create({'user_id': student.gitlab_id,
                                                            'access_level': gitlab.const.DEVELOPER_ACCESS})
                    self.object.students.add(student)
                    messages.success(self.request, "Student was successfully added")
                    return HttpResponseRedirect(self.object.get_absolute_url())
                except GitlabGetError:
                    messages.error(self.request, "Student has no account on GitLab.")
                except Exception as e:
                    messages.error(self.request, "Student has no account on GitLab.")

        elif 'remove_student' in request.POST:
            student_id = request.POST.get('student_id')
            if student_id:
                try:
                    group = gl.groups.get(self.object.gitlab_id)
                    subgroups = group.subgroups.list(all=True)
                    members_group = gl.groups.get(subgroups[1].id)
                    student = get_object_or_404(Student, id=student_id)
                    member = members_group.members.get(student.gitlab_id)
                    member.delete()
                    self.object.students.remove(student)
                    return HttpResponseRedirect(self.object.get_absolute_url())
                except GitlabGetError:
                    messages.error(self.request, "Student is no longer a GitLab group member.")
                    self.object.students.remove(student)
                except Exception as e:
                    messages.error(self.request, f"Student is no longer a GitLab group member: {e}.")

        elif 'fork_projects' in request.POST:
            assignment_id = request.POST.get('assignment_id')
            assignment = get_object_or_404(Assignment, pk=assignment_id)
            try:
                    gitlab_template_id = assignment.template_id
                    assignments_group = gl.groups.get(assignment.gitlab_id)
                    classroom_group = gl.groups.get(self.object.gitlab_id)
                    members_group = self.create_or_get_subgroup(classroom_group, 'MEMBERS')
                    self.fork_project_for_students(assignments_group, gitlab_template_id, members_group)
                    messages.success(self.request, "Projects successfully forked for all students.")
            except Exception as e:
                    messages.error(self.request, f"An error occurred during forking: {e}")

            return HttpResponseRedirect(self.object.get_absolute_url())

        return self.render_to_response(self.get_context_data())

    def create_or_get_subgroup(self, parent_group, subgroup_name):
        gl = gitlab.Gitlab('https://gitlab-stud.elka.pw.edu.pl', private_token=self.request.session["access_token"])
        subgroups = parent_group.subgroups.list(all=True)
        for subgroup in subgroups:
            if subgroup.name == subgroup_name:
                return gl.groups.get(subgroup.id)
        subgroup_data = {
            'name': subgroup_name,
            'path': subgroup_name,
            'parent_id': parent_group.id
        }
        return gl.groups.create(subgroup_data)

    def fork_project_for_students(self, assignments_group, base_project_id, student_group):
        user = self.request.user
        gl = gitlab.Gitlab('https://gitlab-stud.elka.pw.edu.pl', private_token=self.request.session["access_token"])
        students = gl.groups.get(student_group.id).members.list(all=True)
        base_project = gl.projects.get(base_project_id)
        for student in students:
            if int(student.id) != int(user.gitlab_id):
                # Sanitize the project name and path
                personal_group_name = sanitize_name(f"{assignments_group.name}_{student.username}")
                existing_projects = gl.projects.list(search=f"{personal_group_name}_project")
                project_exists = any(proj for proj in existing_projects if proj.namespace['id'] == assignments_group.id)
                if not project_exists:
                    sanitized_project_name = sanitize_name(f"{personal_group_name}_project")
                    forked_project_data = base_project.forks.create({
                        'namespace': assignments_group.id,
                        'name': sanitized_project_name,
                        'path': sanitized_project_name
                    })
                    forked_project = gl.projects.get(forked_project_data.id)

                    forked_project.members.create({
                        'user_id': student.id,
                        'access_level': gitlab.const.AccessLevel.DEVELOPER
                    })
                    print(f"Project forked for {student.username} in subgroup {personal_group_name}")

        return self.render_to_response(self.get_context_data())

def sanitize_name(name):
        # Replace any invalid characters with '_'
        sanitized_name = re.sub(r'[^a-zA-Z0-9_\-.]', '_', name)
        # Ensure the name does not start with '-', end with '.', '.git', or '.atom'
        sanitized_name = sanitized_name.strip('-.')
        return sanitized_name

class ClassroomCreateView(LoginRequiredMixin, generic.CreateView):
    model = Classroom
    fields = ["title", "description", "organization"]
    success_url = reverse_lazy("gitlab_classroom:classroom-list")
    template_name = "gitlab_classroom/classroom_form.html"
    
    def form_valid(self, form):
        user = self.request.user
        form.instance.teacher = user
        response = super().form_valid(form)

        try:
            access_token = self.request.session["access_token"]
        except KeyError:
            return HttpResponse(status=403)  # Forbidden if no access token

        gl = gitlab.Gitlab('https://gitlab-stud.elka.pw.edu.pl', private_token=access_token)

        # Sanitize the title to create a valid path
        sanitized_title = re.sub(r'[^a-zA-Z0-9_\-.]', '_', self.object.title.lower()).strip('-.')

        group_data = {
            'name': self.object.title,
            'path': sanitized_title,
            'description': self.object.description
        }

        try:
            group = gl.groups.create(group_data)
        except gitlab.exceptions.GitlabCreateError:
            self.object.delete()  # Clean up the created object on failure
            return HttpResponse(status=500)  # Internal Server Error

        # Create members and assignments subgroups
        def create_subgroup(name_suffix, description):
            subgroup_path = f"{group_data['path']}_{name_suffix}".strip('-.')

            subgroup_data = {
                "name": name_suffix,

templates/gitlab_classroom/assignment_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}  <!-- Ensure this is correct, it should be crispy_forms_tags -->
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>Delete Assignment</h1>
            <div class="alert alert-warning" role="alert">
                <p>Are you sure you want to delete the assignment <strong>{{ classroom }}</strong>?</p>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group">
                    <input type="submit" value="Delete" class="btn btn-danger"/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/gitlab_classroom/assignment_detail.html
{% extends "base.html"%}
{% load crispy_forms_filters %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <h1 class="card-title mb-0">{{ assignment.title }}</h1> <!-- mb-0 removes bottom margin from h1 if any -->
                    </div>
                    <h6>Classroom: {{assignment.classroom.title}}</h6>
                    <h6 class="text-muted">Creation date: {{ assignment.creation_date }}</h6>
                    <h6 class="text-muted">Deadline: {{ assignment.deadline }}</h6>
                    <p class="card-text">Description: {{ assignment.description }}</p>
                    <p class="card-text">Template ID: {{ assignment.template_id }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/gitlab_classroom/assignment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}  <!-- Ensure this is correct, it should be crispy_forms_tags -->
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="form-group">
                <h1 class="mb-4">{{ object|yesno:"Update,Create" }} Assignment</h1>
                <form action="" method="POST" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="mt-3">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/gitlab_classroom/assignment_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Your Assignments</h1>
    </div>
    
    <form method="get" action="" class="d-flex align-items-center mb-3">
        {{ search_form|crispy }}
        <button class="btn btn-secondary ms-2 mb-2" type="submit">🔎 Search</button>
    </form>

    {% if assignment_list %}
    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>Classroom</th>
                <th>Title</th>
                <th>Deadline</th>
                <th>Repository</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for assignment in assignment_list %}
            <tr>
                <td>{{ assignment.classroom.title }}</td>
                <td><a href="{{ assignment.get_absolute_url }}" class="title">{{ assignment.title }}</a></td>
                <td>{{ assignment.deadline }}</td>
                <td>
                {% if assignment.repo_url %}
                    <a href="{{ assignment.repo_url }}" class="btn btn-primary">Repository</a>
                {% else %}
                    <span class="text-danger">Repository URL not available</span>
                {% endif %}
                </td>
                <td><a class="btn btn-info" href="{% url 'gitlab_classroom:assignment-update' pk=assignment.id %}">Update</a></td>
                <td><a class="btn btn-danger" href="{% url 'gitlab_classroom:assignment-delete' pk=assignment.id %}" onclick="return confirm('Are you sure you want to delete this assignment?');">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h2 class="text-center">No assignments found.</h2>
    {% endif %}
</div>
{% endblock %}

templates/gitlab_classroom/classroom_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}  <!-- Ensure this is correct, it should be crispy_forms_tags -->
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>Delete Classroom</h1>
            <div class="alert alert-warning" role="alert">
                <p>Are you sure you want to delete the classroom <strong>{{ classroom }}</strong>?</p>
                <p><i>All the assignments will be deleted with this classroom!!</i></p>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group">
                    <input type="submit" value="Delete" class="btn btn-danger"/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/gitlab_classroom/classroom_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}

<div class="container mt-5">
    <h1 class="mb-5">{{ classroom.title }} <small class="text-muted">Classroom ID: {{classroom.gitlab_id}}</small></h1>
    <div class="row">
        <!-- Assignments Section -->
        <div class="col-md-6">
            <div class="mb-4">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h2>Assignments:</h2>
                    <a href="{% url 'gitlab_classroom:assignment-create' pk=classroom.id %}" type="submit" name="add_assignment" class="btn btn-primary mb-0">+ Add Assignment</a>
                </div>
            </div>
            <ul class="list-group mt-3">
                {% for assignment in classroom.assignment.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{{assignment.get_absolute_url}}" class="assignment-title d-block mb-2">{{ assignment.title }}</a>
                        <div class="d-flex flex-wrap align-items-center justify-content-center">
                                {% if assignment.repo_url %}
                                        <a href="{{ assignment.repo_url }}" class="btn btn-primary">Repository</a>
                                    {% else %}
                                        <span class="text-danger">Repository URL not available</span>
                                {% endif %}
                                <form method="post" action="">
                                    {% csrf_token %}
                                    <input type="hidden" name="assignment_id" value="{{ assignment.id }}">
                                    <button type="submit" name="fork_projects" class="btn btn-success me-2 mb-2 ms-2">Fork</button>
                                </form>
                        </div>
                </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Students Section -->
        <div class="col-md-6">
            <div class="mb-4">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h2>Students:</h2>
                    <form method="post" class="d-flex align-items-center me-2">
                        {% csrf_token %}
                        <div class="d-flex align-items-center">
                            {{ add_student_form|crispy }}
                            <button type="submit" name="add_student" class="btn btn-primary m-1">Add Student</button>
                        </div>
                    </form>
                </div>
            </div>
            <ul class="list-group mt-3">
                {% for student in classroom.students.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{{student.get_absolute_url}}">{{ student.first_name }} {{ student.second_name }}</a>
                    <form method="post" class="form-inline">
                        {% csrf_token %}
                        <input type="hidden" name="student_id" value="{{ student.id }}">
                        <button type="submit" name="remove_student" class="btn btn-danger m-2">Remove</button>
                    </form>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/gitlab_classroom/classroom_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}  <!-- Ensure this is correct, it should be crispy_forms_tags -->
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="form-group">
                <h1 class="mb-4">{{ object|yesno:"Update,Create" }} Classroom</h1>
                <form action="" method="POST" novalidate>  <!-- Removed 'nonvalidate' typo -->
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="mt-3">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/gitlab_classroom/classroom_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Your classrooms</h1>
        <a class="btn btn-primary" href="{% url 'gitlab_classroom:classroom-create' %}">+ Add Classroom</a>
    </div>
    
    <form method="get" action="" class="d-flex align-items-center mb-3">
        {{ search_form|crispy }}
        <button class="btn btn-secondary ms-2 mb-2" type="submit">🔎 Search</button>
    </form>

    {% if classroom_list %}
    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for classroom in classroom_list %}
            <tr>
                <td>{{ classroom.id }}</td>
                <td><a href="{{ classroom.get_absolute_url }}" class="title">{{ classroom.title }}</a></td>
                <td><a class="btn btn-info" href="{% url 'gitlab_classroom:classroom-update' pk=classroom.id %}">Update</a></td>
                <td><a class="btn btn-danger" href="{% url 'gitlab_classroom:classroom-delete' pk=classroom.id %}" onclick="return confirm('Are you sure?');">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h2 class="text-center">There are no classrooms available.</h2>
    {% endif %}
</div>
{% endblock %}

templates/gitlab_classroom/index.html
{% extends "base.html" %}
{% block title %}
    <title>User Profile</title>
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="card shadow-lg" style="max-width: 400px; margin: auto;">
            <div class="card-body text-center">
                <h5 class="card-title">{{ name }}</h5>
                <hr>
                <p class="card-text">{{email}}</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/gitlab_classroom/student_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}  <!-- Ensure this is correct, it should be crispy_forms_tags -->
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>Delete Student</h1>
            <div class="alert alert-warning" role="alert">
                <p>Are you sure you want to delete the student <strong>{{ student }}</strong>?</p>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group">
                    <input type="submit" value="Delete" class="btn btn-danger"/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/gitlab_classroom/student_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Students</h1>
        <div class="d-flex align-items-center ms-auto">
            <form id="uploadForm" method="post" enctype="multipart/form-data" class="me-2">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="file" id="fileInput" name="file" style="display: none;" onchange="document.getElementById('uploadForm').submit();">
                <button type="button" class="btn btn-success me-2 mb-2" onclick="document.getElementById('fileInput').click();">
                    Upload Students
                </button>
            </form>            
            <form method="post" action="" class="me-2">
                {% csrf_token %}
                <button type="submit" name="check_gitlab" class="btn btn-primary me-2 mb-2">Check GitLab Accounts</button>
            </form>
            <a class="btn btn-primary me-2" href="{% url 'gitlab_classroom:student-create' %}">+ Add Student</a>
        </div>        
    </div>

    <div class="d-flex justify-content-between align-items-center mb-3">
        <form method="get" action="" class="d-flex align-items-center w-100">
            {{ search_form|crispy }}
            <button class="btn btn-secondary m-2" type="submit">🔎 Search</button>
        </form>
    </div>

    {% if student_list %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>GitLab username</th>
                    <th>GitLab Sync</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for student in student_list %}
                <tr>
                    <td>{{ student.id }}</td>
                    <td><a href="{{ student.get_absolute_url }}" class="title">{{ student.gitlab_username }}</a></td>
                    <td>
                        {% if student.gl_flag %}
                            <span class="text-success">&#10003;</span> <!-- Tick for True -->
                        {% else %}
                            <span class="text-danger">&#10007;</span> <!-- Cross for False -->
                        {% endif %}
                    </td>
                    <td><a class="btn btn-info" href="{% url 'gitlab_classroom:student-update' pk=student.id %}">Update</a></td>
                    <td><a class="btn btn-danger" href="{% url 'gitlab_classroom:student-delete' pk=student.id %}" onclick="return confirm('Are you sure?');">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <h2 class="text-center">There are no students.</h2>
    {% endif %}
</div>
{% endblock %}