accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view


urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout")
]


app_name = "accounts"

gitlab_classroom/urls.py
from django.urls import path
from gitlab_classroom.views import (index,
                          ClassroomsListView,
                          AssignmentsListView,
                          ClassroomsDetailView,
                          AssignmentsDetailView,
                          ClassroomCreateView,
                          ClassroomUpdateView,
                          ClassroomDeleteView,
                          AssignmentCreateView,
                          AssignmentUpdateView,
                          AssignmentDeleteView,
                          StudentsListView,
                          StudentsDetailView,
                          StudentCreateView,
                          StudentUpdateView,
                          StudentDeleteView)


urlpatterns = [
    path("", index, name="index"),
    path("classrooms/", ClassroomsListView.as_view(), name="classroom-list"),
    path("assignments/", AssignmentsListView.as_view(), name="assignment-list"),
    path("classrooms/<int:pk>/", ClassroomsDetailView.as_view(), name="classroom-detail"),
    path("assignments/<int:pk>/", AssignmentsDetailView.as_view(), name="assignment-detail"),
    path("classrooms/<int:pk>/assignments/create/", AssignmentCreateView.as_view(), name="assignment-create"),
    path("assignments/<int:pk>/update/", AssignmentUpdateView.as_view(), name="assignment-update"),
    path("assignments/<int:pk>/delete/", AssignmentDeleteView.as_view(), name="assignment-delete"),
    path("classrooms/create/", ClassroomCreateView.as_view(), name="classroom-create"),
    path("classrooms/<int:pk>/update/", ClassroomUpdateView.as_view(), name="classroom-update"),
    path("classrooms/<int:pk>/delete/", ClassroomDeleteView.as_view(), name="classroom-delete"),
    path("students/", StudentsListView.as_view(), name="student-list"),
    path("students/<int:pk>/", StudentsDetailView.as_view(), name="student-detail"),
    path("students/create/", StudentCreateView.as_view(), name="student-create"),
    path("students/<int:pk>/update/", StudentUpdateView.as_view(), name="student-update"),
    path("students/<int:pk>/delete/", StudentDeleteView.as_view(), name="student-delete"),
]


app_name = "gitlab_classroom" 

gitlab_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gitlab_classroom.urls", namespace="gitlab_classroom")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("__debug__/", include("debug_toolbar.urls"))
]

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>GitLab Classroom</title>
</head>
<body>

<nav class="navbar navbar-expand-lg" style="justify-content: center;">
    <a href="https://gitlab-stud.elka.pw.edu.pl">
        <img src="{% static 'icons/project_avatar.jpg' %}" alt="GitLab Logo">
    </a>
    <div class="application-name">
        <a href="https://gitlab-stud.elka.pw.edu.pl">GitLab Classroom</a>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gitlab_classroom:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gitlab_classroom:classroom-list' %}">Classrooms</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gitlab_classroom:assignment-list' %}">Assignments</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gitlab_classroom:student-list' %}">Students</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js" integrity="sha384-pzjw8f+ua7Kw1TIqM7rDAKARUOAeLBV7+U6Xyk5CE2jF5v0j5a7RyfPo5Pv5Y6Xl" crossorigin="anonymous"></script>
</body>
</html> 

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">Prev</a>
                </li>
            {% endif %}
            <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">Next</a></li>
            {% endif %}
        </ul>
{% endif %}